#ifndef MONGOCRYPT_EXPORT_H
#define MONGOCRYPT_EXPORT_H

/* This file would typically be generated by libmongocrypt's CMake build process
 * so it must exist when building libmongocrypt as a submodule via Autotools. We
 * need only ensure this file exists and expected constants are defined, since
 * libmongocrypt APIs will not actually be exported.
 *
 * See: https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html */
#define MONGOCRYPT_EXPORT
#define MONGOCRYPT_NO_EXPORT
#define MONGOCRYPT_DEPRECATED
#define MONGOCRYPT_DEPRECATED_EXPORT
#define MONGOCRYPT_DEPRECATED_NO_EXPORT

#endif /* MONGOCRYPT_EXPORT_H */
