--TEST--
Tests of Binary subtype 9, Vectors, with dtype FLOAT32: FLOAT32 with padding
--XFAIL--
Document memory leak (PHPC-2648)
--DESCRIPTION--
Generated by scripts/convert-bson-binary-vector-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/basic.inc';

// Vector [127,7] with padding 3
echo 'Vector type Float32 does not support padding: 3', "\n";

throws(function() {
    var_dump(MongoDB\BSON\Document::fromBSON(hex2bin('1C00000005766563746F72000A0000000927030000FE420000E04000')));
}, 'MongoDB\Driver\Exception\InvalidArgumentException');

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
Vector type Float32 does not support padding: 3
OK: Got MongoDB\Driver\Exception\InvalidArgumentException
===DONE===