--TEST--
Tests of Binary subtype 9, Vectors, with dtype INT8: Overflow Vector INT8
--DESCRIPTION--
Generated by scripts/convert-bson-binary-vector-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/basic.inc';

// Vector [128] with padding 0
$vector = array (
  0 => 128,
);

throws(function() use ($vector) {
    var_dump(MongoDB\BSON\Binary::fromVector($vector, \MongoDB\BSON\VectorType::Int8));
}, 'MongoDB\Driver\Exception\InvalidArgumentException');

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
OK: Got MongoDB\Driver\Exception\InvalidArgumentException
===DONE===