--TEST--
Tests of Binary subtype 9, Vectors, with dtype INT8: Empty Vector INT8
--DESCRIPTION--
Generated by scripts/convert-bson-binary-vector-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/basic.inc';

// Vector [] with padding 0
$vector = array (
);

$binary = MongoDB\BSON\Binary::fromVector($vector, \MongoDB\BSON\VectorType::Int8);
echo bin2hex((string) MongoDB\BSON\Document::fromPHP(['vector' => $binary])), "\n";

$bson = MongoDB\BSON\Document::fromBSON(hex2bin('1400000005766563746F72000200000009030000'));
var_dump($binary == $bson['vector']);

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
1400000005766563746f72000200000009030000
bool(true)
===DONE===