--TEST--
Tests of Binary subtype 9, Vectors, with dtype PACKED_BIT: Negative padding PACKED_BIT
--DESCRIPTION--
Generated by scripts/convert-bson-binary-vector-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/basic.inc';

// Vector [1] with padding -1
echo 'Expected padding [0..7], -1 given', "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
Expected padding [0..7], -1 given
===DONE===