--TEST--
Tests of Binary subtype 9, Vectors, with dtype PACKED_BIT: Overflow Vector PACKED_BIT
--DESCRIPTION--
Generated by scripts/convert-bson-binary-vector-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/basic.inc';

// Vector [256] with padding 0
echo 'Expected vector[0] to be an unsigned int8, 256 given', "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
Expected vector[0] to be an unsigned int8, 256 given
===DONE===