/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: fed93e737f61211a869f684f5a47cf59b8289d38 */

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_MongoDB_BSON_JavascriptInterface_getCode, 0, 0, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_MongoDB_BSON_JavascriptInterface_getScope arginfo_class_MongoDB_BSON_JavascriptInterface_getCode

#define arginfo_class_MongoDB_BSON_JavascriptInterface___toString arginfo_class_MongoDB_BSON_JavascriptInterface_getCode




static const zend_function_entry class_MongoDB_BSON_JavascriptInterface_methods[] = {
	ZEND_ABSTRACT_ME_WITH_FLAGS(MongoDB_BSON_JavascriptInterface, getCode, arginfo_class_MongoDB_BSON_JavascriptInterface_getCode, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(MongoDB_BSON_JavascriptInterface, getScope, arginfo_class_MongoDB_BSON_JavascriptInterface_getScope, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_ABSTRACT_ME_WITH_FLAGS(MongoDB_BSON_JavascriptInterface, __toString, arginfo_class_MongoDB_BSON_JavascriptInterface___toString, ZEND_ACC_PUBLIC|ZEND_ACC_ABSTRACT)
	ZEND_FE_END
};
