if test "$PHP_MONGODB_CLIENT_SIDE_ENCRYPTION" = "yes"; then
  MONGOCRYPT_CURRENT_FILE=[]PHP_EXT_SRCDIR(mongodb)[/src/LIBMONGOCRYPT_VERSION_CURRENT]
  MONGOCRYPT_BUILD_VERSION=$(cat $MONGOCRYPT_CURRENT_FILE)

  AC_SUBST(MONGOCRYPT_BUILD_VERSION)
fi
