--TEST--
Binary type: subtype 0x01
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('0F0000000578000200000001FFFF00');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON($bson)), "\n";

$json = '{"x" : {"$binary" : "//8=", "$type" : "01"}}';

// extJSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON(fromJSON($json))), "\n";

// extJSON to Canonical BSON
echo bin2hex(fromJSON($json)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
0f0000000578000200000001ffff00
{"x":{"$binary":"\/\/8=","$type":"01"}}
{"x":{"$binary":"\/\/8=","$type":"01"}}
0f0000000578000200000001ffff00
===DONE===