--TEST--
Binary type: $type query operator (conflicts with legacy $binary form with $type field)
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('180000000378001000000010247479706500020000000000');
$canonicalExtJson = '{"x" : { "$type" : {"$numberInt": "2"}}}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
180000000378001000000010247479706500020000000000
{"x":{"$type":{"$numberInt":"2"}}}
180000000378001000000010247479706500020000000000
===DONE===