--TEST--
Javascript Code with Scope: Empty code string, non-empty scope
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('1D0000000F61001500000001000000000C000000107800010000000000');
$canonicalExtJson = '{"a" : {"$code" : "", "$scope" : {"x" : {"$numberInt": "1"}}}}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
1d0000000f61001500000001000000000c000000107800010000000000
{"a":{"$code":"","$scope":{"x":{"$numberInt":"1"}}}}
1d0000000f61001500000001000000000c000000107800010000000000
===DONE===