--TEST--
Javascript Code: Embedded nulls
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('190000000261000D0000006162006261620062616261620000');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON($bson)), "\n";

$json = '{"a" : "ab\\u0000bab\\u0000babab"}';

// extJSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON(fromJSON($json))), "\n";

// extJSON to Canonical BSON
echo bin2hex(fromJSON($json)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
190000000261000d0000006162006261620062616261620000
{"a":"ab\u0000bab\u0000babab"}
{"a":"ab\u0000bab\u0000babab"}
190000000261000d0000006162006261620062616261620000
===DONE===