--TEST--
DateTime: Y10K
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('1000000009610000DC1FD277E6000000');
$canonicalExtJson = '{"a":{"$date":{"$numberLong":"253402300800000"}}}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
1000000009610000dc1fd277e6000000
{"a":{"$date":{"$numberLong":"253402300800000"}}}
1000000009610000dc1fd277e6000000
===DONE===