--TEST--
DBPointer type (deprecated): With two-byte UTF-8
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('1B0000000C610003000000C3A90056E1FC72E0C917E9C471416100');
$convertedBson = hex2bin('2B0000000361002300000002247265660003000000C3A900072469640056E1FC72E0C917E9C47141610000');
$canonicalExtJson = '{"a": {"$dbPointer": {"$ref": "é", "$id": {"$oid": "56e1fc72e0c917e9c4714161"}}}}';
$convertedExtJson = '{"a": {"$ref": "é", "$id": {"$oid": "56e1fc72e0c917e9c4714161"}}}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
1b0000000c610003000000c3a90056e1fc72e0c917e9c471416100
{"a":{"$dbPointer":{"$ref":"\u00e9","$id":{"$oid":"56e1fc72e0c917e9c4714161"}}}}
1b0000000c610003000000c3a90056e1fc72e0c917e9c471416100
===DONE===