--TEST--
Decimal128: [decq022] Normality
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/basic.inc';

$canonicalBson = hex2bin('18000000136400C7711CC7B548F377DC80A131C836403000');
$canonicalExtJson = '{"d" : {"$numberDecimal" : "1111111111111111111111111111111111"}}';

// Canonical BSON -> Native -> Canonical BSON
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> BSON object -> Canonical BSON
echo bin2hex((string) MongoDB\BSON\Document::fromBSON($canonicalBson)), "\n";

// Canonical BSON -> Canonical extJSON
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical BSON -> BSON object -> Canonical extJSON
echo json_canonicalize(MongoDB\BSON\Document::fromBSON($canonicalBson)->toCanonicalExtendedJSON()), "\n";

// Canonical extJSON -> Canonical BSON
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

// Canonical extJSON -> BSON object -> Canonical BSON
echo bin2hex((string) MongoDB\BSON\Document::fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
18000000136400c7711cc7b548f377dc80a131c836403000
18000000136400c7711cc7b548f377dc80a131c836403000
{"d":{"$numberDecimal":"1111111111111111111111111111111111"}}
{"d":{"$numberDecimal":"1111111111111111111111111111111111"}}
18000000136400c7711cc7b548f377dc80a131c836403000
18000000136400c7711cc7b548f377dc80a131c836403000
===DONE===