--TEST--
Decimal128: [decq840] VG testcase
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('180000001364003C17258419D710C42F0000000000002400');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toJSON($bson)), "\n";

$json = '{"d" : {"$numberDecimal" : "8.81125000000001349436E-1548"}}';

// extJSON to Canonical extJSON
echo json_canonicalize(toJSON(fromJSON($json))), "\n";

// extJSON to Canonical BSON
echo bin2hex(fromJSON($json)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
180000001364003c17258419d710c42f0000000000002400
{"d":{"$numberDecimal":"8.81125000000001349436E-1548"}}
{"d":{"$numberDecimal":"8.81125000000001349436E-1548"}}
180000001364003c17258419d710c42f0000000000002400
===DONE===