--TEST--
Decimal128: [decq626] fold-down full sequence
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('180000001364000000A0DEC5ADC935360000000000FE5F00');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON($bson)), "\n";

$json = '{"d" : {"$numberDecimal" : "1.000000000000000000000E+6132"}}';

// extJSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON(fromJSON($json))), "\n";

// extJSON to Canonical BSON
echo bin2hex(fromJSON($json)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
180000001364000000a0dec5adc935360000000000fe5f00
{"d":{"$numberDecimal":"1.000000000000000000000E+6132"}}
{"d":{"$numberDecimal":"1.000000000000000000000E+6132"}}
180000001364000000a0dec5adc935360000000000fe5f00
===DONE===