--TEST--
Decimal128: [decq840] VG testcase
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/basic.inc';

$canonicalBson = hex2bin('180000001364003C17258419D710C42F0000000000002400');
$canonicalExtJson = '{"d" : {"$numberDecimal" : "8.81125000000001349436E-1548"}}';

// Canonical BSON -> Native -> Canonical BSON
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> BSON object -> Canonical BSON
echo bin2hex((string) MongoDB\BSON\Document::fromBSON($canonicalBson)), "\n";

// Canonical BSON -> Canonical extJSON
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical BSON -> BSON object -> Canonical extJSON
echo json_canonicalize(MongoDB\BSON\Document::fromBSON($canonicalBson)->toCanonicalExtendedJSON()), "\n";

// Canonical extJSON -> Canonical BSON
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

// Canonical extJSON -> BSON object -> Canonical BSON
echo bin2hex((string) MongoDB\BSON\Document::fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
180000001364003c17258419d710c42f0000000000002400
180000001364003c17258419d710c42f0000000000002400
{"d":{"$numberDecimal":"8.81125000000001349436E-1548"}}
{"d":{"$numberDecimal":"8.81125000000001349436E-1548"}}
180000001364003c17258419d710c42f0000000000002400
180000001364003c17258419d710c42f0000000000002400
===DONE===