--TEST--
Decimal128: [decq618] fold-down full sequence
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('180000001364000000004A48011416954508000000FE5F00');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toJSON($bson)), "\n";

$json = '{"d" : {"$numberDecimal" : "1.0000000000000000000000000E+6136"}}';

// extJSON to Canonical extJSON
echo json_canonicalize(toJSON(fromJSON($json))), "\n";

// extJSON to Canonical BSON
echo bin2hex(fromJSON($json)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
180000001364000000004a48011416954508000000fe5f00
{"d":{"$numberDecimal":"1.0000000000000000000000000E+6136"}}
{"d":{"$numberDecimal":"1.0000000000000000000000000E+6136"}}
180000001364000000004a48011416954508000000fe5f00
===DONE===