--TEST--
Decimal128: [decq002] (mostly derived from the Strawman 4 document and examples)
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('18000000136400EE020000000000000000000000003CB000');
$canonicalExtJson = '{"d" : {"$numberDecimal" : "-7.50"}}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
18000000136400ee020000000000000000000000003cb000
{"d":{"$numberDecimal":"-7.50"}}
18000000136400ee020000000000000000000000003cb000
===DONE===