--TEST--
Decimal128: [decq632] fold-down full sequence
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('18000000136400000064A7B3B6E00D000000000000FE5F00');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toJSON($bson)), "\n";

$json = '{"d" : {"$numberDecimal" : "1.000000000000000000E+6129"}}';

// extJSON to Canonical extJSON
echo json_canonicalize(toJSON(fromJSON($json))), "\n";

// extJSON to Canonical BSON
echo bin2hex(fromJSON($json)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
18000000136400000064a7b3b6e00d000000000000fe5f00
{"d":{"$numberDecimal":"1.000000000000000000E+6129"}}
{"d":{"$numberDecimal":"1.000000000000000000E+6129"}}
18000000136400000064a7b3b6e00d000000000000fe5f00
===DONE===