--TEST--
Decimal128: [decq842] VG testcase
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('180000001364000000FED83F4E7C9FE4E269E38A5BCD1700');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toJSON($bson)), "\n";

$json = '{"d" : {"$numberDecimal" : "7.049000000000010795488000000000000E-3097"}}';

// extJSON to Canonical extJSON
echo json_canonicalize(toJSON(fromJSON($json))), "\n";

// extJSON to Canonical BSON
echo bin2hex(fromJSON($json)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
180000001364000000fed83f4e7c9fe4e269e38a5bcd1700
{"d":{"$numberDecimal":"7.049000000000010795488000000000000E-3097"}}
{"d":{"$numberDecimal":"7.049000000000010795488000000000000E-3097"}}
180000001364000000fed83f4e7c9fe4e269e38a5bcd1700
===DONE===