--TEST--
Decimal128: [basx212] Numbers with E
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('18000000136400F1040000000000000000000000002E3000');
$canonicalExtJson = '{"d" : {"$numberDecimal" : "0.000001265"}}';
$degenerateExtJson = '{"d" : {"$numberDecimal" : "126.5E-8"}}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

// Degenerate extJSON -> Canonical BSON 
echo bin2hex(fromJSON($degenerateExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
18000000136400f1040000000000000000000000002e3000
{"d":{"$numberDecimal":"0.000001265"}}
18000000136400f1040000000000000000000000002e3000
18000000136400f1040000000000000000000000002e3000
===DONE===