--TEST--
Decimal128: Special - Invalid representation treated as 0E3
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('18000000136400FFFFFFFFFFFFFFFFFFFFFFFFFFFF116C00');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toJSON($bson)), "\n";

$json = '{"d" : {"$numberDecimal" : "0E+3"}}';

// extJSON to Canonical extJSON
echo json_canonicalize(toJSON(fromJSON($json))), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
18000000136400ffffffffffffffffffffffffffff116c00
{"d":{"$numberDecimal":"0E+3"}}
{"d":{"$numberDecimal":"0E+3"}}
===DONE===