--TEST--
Decimal128: Regular - Smallest with Trailing Zeros
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('1800000013640040EF5A07000000000000000000002A3000');
$canonicalExtJson = '{"d" : {"$numberDecimal" : "0.00123400000"}}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
1800000013640040ef5a07000000000000000000002a3000
{"d":{"$numberDecimal":"0.00123400000"}}
1800000013640040ef5a07000000000000000000002a3000
===DONE===