--TEST--
Decimal128: [decq200] underflow edge cases (Subnormal)
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('18000000136400FFFFFFFF095BC138938D44C64D31008000');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toJSON($bson)), "\n";

$json = '{"d" : {"$numberDecimal" : "-999999999999999999999999999999999e-6176"}}';

// extJSON to Canonical extJSON
echo json_canonicalize(toJSON(fromJSON($json))), "\n";

$canonicalJson = '{"d" : {"$numberDecimal" : "-9.99999999999999999999999999999999E-6144"}}';

// Canonical extJSON to Canonical extJSON
echo json_canonicalize(toJSON(fromJSON($canonicalJson))), "\n";

// extJSON to Canonical BSON
echo bin2hex(fromJSON($json)), "\n";

// Canonical extJSON to Canonical BSON
echo bin2hex(fromJSON($canonicalJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
18000000136400ffffffff095bc138938d44c64d31008000
{"d":{"$numberDecimal":"-9.99999999999999999999999999999999E-6144"}}
{"d":{"$numberDecimal":"-9.99999999999999999999999999999999E-6144"}}
{"d":{"$numberDecimal":"-9.99999999999999999999999999999999E-6144"}}
18000000136400ffffffff095bc138938d44c64d31008000
18000000136400ffffffff095bc138938d44c64d31008000
===DONE===