--TEST--
Decimal128: [basx217] Numbers with E
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('18000000136400F1040000000000000000000000003E3000');
$canonicalExtJson = '{"d" : {"$numberDecimal" : "126.5"}}';
$degenerateExtJson = '{"d" : {"$numberDecimal" : "126.5E-0"}}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

// Degenerate extJSON -> Canonical BSON 
echo bin2hex(fromJSON($degenerateExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
18000000136400f1040000000000000000000000003e3000
{"d":{"$numberDecimal":"126.5"}}
18000000136400f1040000000000000000000000003e3000
18000000136400f1040000000000000000000000003e3000
===DONE===