--TEST--
Decimal128: [dqbsr431] check rounding modes heeded (Rounded)
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('1800000013640099761CC7B548F377DC80A131C836FE2F00');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON($bson)), "\n";

$json = '{"d" : {"$numberDecimal" : "1.1111111111111111111111111111123450"}}';

// extJSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON(fromJSON($json))), "\n";

$canonicalJson = '{"d" : {"$numberDecimal" : "1.111111111111111111111111111112345"}}';

// Canonical extJSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON(fromJSON($canonicalJson))), "\n";

// extJSON to Canonical BSON
echo bin2hex(fromJSON($json)), "\n";

// Canonical extJSON to Canonical BSON
echo bin2hex(fromJSON($canonicalJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
1800000013640099761cc7b548f377dc80a131c836fe2f00
{"d":{"$numberDecimal":"1.111111111111111111111111111112345"}}
{"d":{"$numberDecimal":"1.111111111111111111111111111112345"}}
{"d":{"$numberDecimal":"1.111111111111111111111111111112345"}}
1800000013640099761cc7b548f377dc80a131c836fe2f00
1800000013640099761cc7b548f377dc80a131c836fe2f00
===DONE===