--TEST--
ObjectId: All ones
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('14000000076100FFFFFFFFFFFFFFFFFFFFFFFF00');
$canonicalExtJson = '{"a" : {"$oid" : "ffffffffffffffffffffffff"}}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
14000000076100ffffffffffffffffffffffff00
{"a":{"$oid":"ffffffffffffffffffffffff"}}
14000000076100ffffffffffffffffffffffff00
===DONE===