--TEST--
Regular Expression type: regex without options
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('0D0000000B6100616263000000');
$canonicalExtJson = '{"a" : {"$regularExpression" : { "pattern": "abc", "options" : ""}}}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
0d0000000b6100616263000000
{"a":{"$regularExpression":{"pattern":"abc","options":""}}}
0d0000000b6100616263000000
===DONE===