--TEST--
Regular Expression type: flags not alphabetized
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$bson = hex2bin('100000000B6100616263006D69780000');

// BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($bson))), "\n";

$canonicalBson = hex2bin('100000000B610061626300696D780000');

// Canonical BSON to Canonical BSON
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// BSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON($bson)), "\n";

$json = '{"a" : {"$regex" : "abc", "$options" : "imx"}}';

// extJSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON(fromJSON($json))), "\n";

// Canonical BSON to Canonical extJSON
echo json_canonicalize(toExtendedJSON($canonicalBson)), "\n";

// extJSON to Canonical BSON
echo bin2hex(fromJSON($json)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
100000000b610061626300696d780000
100000000b610061626300696d780000
{"a":{"$regex":"abc","$options":"imx"}}
{"a":{"$regex":"abc","$options":"imx"}}
{"a":{"$regex":"abc","$options":"imx"}}
100000000b610061626300696d780000
===DONE===