--TEST--
Symbol: two-byte UTF-8 (é)
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

$canonicalBson = hex2bin('190000000E61000D000000C3A9C3A9C3A9C3A9C3A9C3A90000');
$convertedBson = hex2bin('190000000261000D000000C3A9C3A9C3A9C3A9C3A9C3A90000');
$canonicalExtJson = '{"a": {"$symbol": "éééééé"}}';
$convertedExtJson = '{"a": "éééééé"}';

// Canonical BSON -> Native -> Canonical BSON 
echo bin2hex(fromPHP(toPHP($canonicalBson))), "\n";

// Canonical BSON -> Canonical extJSON 
echo json_canonicalize(toCanonicalExtendedJSON($canonicalBson)), "\n";

// Canonical extJSON -> Canonical BSON 
echo bin2hex(fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
190000000e61000d000000c3a9c3a9c3a9c3a9c3a9c3a90000
{"a":{"$symbol":"\u00e9\u00e9\u00e9\u00e9\u00e9\u00e9"}}
190000000e61000d000000c3a9c3a9c3a9c3a9c3a9c3a90000
===DONE===