--TEST--
Top-level document validity: Bad $timestamp (extra field at same level as $timestamp)
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/tools.php';

throws(function() {
    fromJSON('{"a" : {"$timestamp" : {"t" : "123456789", "i" : "42"}, "unrelated": true } }');
}, 'MongoDB\Driver\Exception\UnexpectedValueException');

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
OK: Got MongoDB\Driver\Exception\UnexpectedValueException
===DONE===