<?php

namespace MongoDB\Write;

/**
 * Result returned by Server and Manager executeWrite() methods processing an
 * InsertBatch.
 *
 * This class may be constructed internally if it will encapsulate a libmongoc
 * data structure.
 */
final class InsertResult implements WriteResult
{
    /**
     * @return integer
     */
    public function getNumInserted() {}

    /**
     * @return GeneratedId[]
     */
    public function getGeneratedIds()
    {
        /* Return an array of identifiers generated by the driver. Each
         * GeneratedId has a batch index and the ID value.
         *
         * This supersedes the identifier-setting hack in the 1.x driver.
         */
    }

    /**
     * @see WriteResult::getInfo()
     */
    public function getInfo() {}

    /**
     * @see WriteResult::getServer()
     */
    public function getServer() {}

    /**
     * @see WriteResult::getWriteConcernErrors()
     */
    public function getWriteConcernErrors() {}

    /**
     * @see WriteResult::getWriteErrors()
     */
    public function getWriteErrors() {}
}
