name: "Check generated arginfo files"

on:
  pull_request:
    branches:
      - "v*.*"
      - "feature/*"
  push:
    branches:
      - "v*.*"
      - "feature/*"

env:
  PHP_VERSION: "8.2"

jobs:
  check-arginfo:
    name: "Check generated arginfo files"
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Checkout"
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          submodules: true

      - name: "Install PHP"
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240  # 2.37.2
        with:
          php-version: "${{ env.PHP_VERSION }}"

      - name: "Run phpize"
        run: phpize

      - name: "Rebuild arginfo files from stubs"
        run: "php ./build/gen_stub.php --force-regeneration"

      - name: "Check arginfo file diff"
        run: git add . -N && git diff --exit-code
