name: "Coding Standards"

on:
  pull_request:
    branches:
      - "v*.*"
      - "feature/*"
  push:
    branches:
      - "v*.*"
      - "feature/*"

env:
  PHP_VERSION: "8.1"

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Checkout"
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          submodules: true

      - name: "Install PHP"
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240  # 2.37.2
        with:
          php-version: "${{ env.PHP_VERSION }}"

      - name: "Configure driver"
        run: .github/workflows/configure.sh

      - name: "Run clang-format"
        run: "make format-check"
