name: "Check validity of composer.json"

on:
  pull_request:
    branches:
      - "v*.*"
      - "feature/*"
  push:
    branches:
      - "v*.*"
      - "feature/*"

jobs:
  composer-validate:
    name: "Check validity of composer.json"
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          submodules: true

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"

      - name: "Run composer validate"
        run: "composer validate --strict"
