name: "Check validity of composer.json"

on:
  pull_request:
    branches:
      - "v*.*"
      - "feature/*"
  push:
    branches:
      - "v*.*"
      - "feature/*"

jobs:
  composer-validate:
    name: "Check validity of composer.json"
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Checkout"
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          submodules: true

      - name: "Install PHP"
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240  # 2.37.2

      - name: "Run composer validate"
        run: "composer validate --strict"
