name: Merge up

on:
  push:
    branches:
      - "v[0-9]+.[0-9x]+"

env:
  GH_TOKEN: ${{ secrets.MERGE_UP_TOKEN }}

jobs:
  merge-up:
    name: Create merge up pull request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          # fetch-depth 0 is required to fetch all branches, not just the branch being built
          fetch-depth: 0
          token: ${{ secrets.MERGE_UP_TOKEN }}

      - name: Create pull request
        id: create-pull-request
        uses: alcaeus/automatic-merge-up-action@a43d2c2d3ed5a92a1fce3e3bde21c27c578f50d3  # 1.0.0
        with:
          ref: ${{ github.ref_name }}
          branchNamePattern: 'v<major>.<minor>'
          devBranchNamePattern: 'v<major>.x'
          ignoredBranches: ${{ vars.IGNORED_MERGE_UP_BRANCHES }}
          enableAutoMerge: true
