name: "System library tests"

on:
  push:
    branches:
      - "build-system-libs"

jobs:
  tests:
    name: "Build"
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          submodules: true

      - name: "Install libmongocrypt"
        uses: ./.github/actions/linux/build-libmongocrypt
        with:
          version: 1.14

      - name: "Build libmongoc"
        uses: ./.github/actions/linux/build-libmongoc
        with:
          version: 2.0.1

      - name: "Build Driver"
        uses: ./.github/actions/linux/build
        with:
          version: "8.4"
          configureOpts: "--with-mongodb-system-libs=yes"

      - name: "Check driver version"
        shell: bash
        run: make show-config

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup MongoDB
        id: setup-mongodb
        uses: ./tests/drivers-evergreen-tools
        with:
          version: "8.0"
          topology: "server"

      - name: "Run Tests"
        run: TEST_PHP_ARGS="-q -x --show-diff -g FAIL,XFAIL,BORK,WARN,LEAK,SKIP" make test
        env:
          MONGODB_URI: ${{ steps.setup-mongodb.outputs.cluster-uri }}
